#!/usr/bin/env python3
"""
bert_filter.py — Filter word_context.py CSV output using BERT-based classifiers.

Three classifiers run on each target_context chunk:

  1. Language — langdetect (lightweight, no neural model)
     Drops rows where English-language probability < --lang-threshold (default 0.85).

  2. Writing quality — heuristic scorer (no ML, no torch required)
     Scores based on function-word ratio, comma density, and separator density.
     Catches keyword strings, SEO spam, and nav menus without loading any model.
     Drops rows below --quality-threshold (default 0.70).

  3. Slang sense disambiguation — bert-base-uncased contextual embeddings
     Only loaded when --slang-defs is provided. Requires torch + transformers.
     Compares the word's contextual embedding to prototype vectors built from
     user-supplied example sentences in slang.yaml.
     Words with both senses: score = cos_sim(context, slang_proto) - cos_sim(context, standard_proto).
     Words with slang examples only: score = cos_sim(context, slang_proto) (0-1 absolute).
     Drops rows below --slang-threshold (default 0.0).
     Rows containing no defined slang word are not affected.

torch and transformers are only required when --slang-defs is passed.
Without it, the script runs on langdetect + pure-Python heuristics only.

"Embeddings" for slang classification are built from samples in slang.yaml.
The yaml content was generated by Claude Sonnet 4.6 and manually edited.

Usage:
    # Language + quality only (no torch needed)
    python bert_filter.py contexts/*.csv -o filtered.csv

    # All three filters (torch required)
    python bert_filter.py contexts/*.csv -o filtered.csv --slang-defs slang.yaml

    # Score everything for threshold calibration
    python bert_filter.py input.csv -o scored.csv --score-all --keep-scores \\
        --slang-defs slang.yaml

    # Stricter slang gate
    python bert_filter.py input.csv -o out.csv --slang-defs slang.yaml \\
        --slang-threshold 0.05
"""

from __future__ import annotations

import argparse
import csv
import glob
import logging
import os
import sys
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Tuple

os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

# torch and transformers are imported lazily — only when --slang-defs is used.
try:
    import torch
    import torch.nn.functional as F
    from transformers import AutoModel, AutoTokenizer  # type: ignore
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

try:
    from langdetect import DetectorFactory, LangDetectException, detect_langs  # type: ignore
    DetectorFactory.seed = 0
    HAS_LANGDETECT = True
except ImportError:
    HAS_LANGDETECT = False

try:
    import yaml  # type: ignore
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

try:
    from tqdm import tqdm  # type: ignore
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(line_buffering=True)  # type: ignore[attr-defined]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stderr)],
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Default model — used only for slang embeddings when --slang-defs is provided
# ---------------------------------------------------------------------------

_BERT_MODEL = "bert-base-uncased"

# ---------------------------------------------------------------------------
# Filter 1 — Language detection (langdetect, no neural model)
# ---------------------------------------------------------------------------

def _english_score(text: str) -> float:
    """Return estimated probability that text is English via langdetect."""
    try:
        for lang in detect_langs(text):
            if lang.lang == "en":
                return float(lang.prob)
        return 0.0
    except LangDetectException:
        return 0.0

# ---------------------------------------------------------------------------
# Filter 2 — Writing quality (heuristic, no ML)
# ---------------------------------------------------------------------------

# Common English function words. Their presence signals grammatical prose;
# their absence signals keyword lists or nav menus.
_FUNCTION_WORDS = frozenset({
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "i", "you", "he", "she", "it", "we", "they", "me", "him", "her", "us",
    "in", "on", "at", "to", "of", "and", "or", "but", "if", "not", "so",
    "for", "with", "as", "by", "from", "do", "does", "did", "will",
    "would", "could", "should", "have", "has", "had", "that", "this",
    "than", "then", "when", "what", "which", "who", "how", "there",
})


def _quality_score(text: str) -> float:
    """Heuristic writing-quality score in [0, 1].

    Penalises keyword strings (low function-word ratio), comma-separated
    lists (high comma density), and nav menus (high pipe/slash density).
    Returns 0.0 for texts shorter than 8 tokens.
    """
    tokens = text.split()
    n = len(tokens)
    if n < 8:
        return 0.0

    lower = [t.strip(".,!?;:\"'()[]{}-").lower() for t in tokens]

    func_ratio    = sum(1 for t in lower if t in _FUNCTION_WORDS) / n
    comma_density = text.count(",") / n
    sep_density   = (text.count("|") + text.count(" / ")) / n

    score = 1.0
    # Function words: strong signal of grammatical prose
    if func_ratio < 0.04:
        score -= 0.50   # almost no function words → keyword list
    elif func_ratio < 0.08:
        score -= 0.20   # few function words → suspicious

    # Comma density: lists are comma-heavy
    if comma_density > 0.12:
        score -= 0.40
    elif comma_density > 0.06:
        score -= 0.15

    # Separator density: nav menus use | and /
    if sep_density > 0.04:
        score -= 0.40

    return max(0.0, min(1.0, score))

# ---------------------------------------------------------------------------
# CSV helpers
# ---------------------------------------------------------------------------

def _read_rows(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _batched(items: list, size: int) -> Iterator[list]:
    for i in range(0, len(items), size):
        yield items[i : i + size]

# ---------------------------------------------------------------------------
# Filter 3 — Slang sense classifier (contextual BERT embeddings)
# ---------------------------------------------------------------------------

def _find_word_positions(tokens: List[str], word_tokens: List[str]) -> List[int]:
    """Return token positions of the first full-word occurrence of word_tokens.

    Checks that the token immediately after the match is not a WordPiece
    continuation (## prefix), preventing 'fire' from matching inside 'fired'.
    Returns [] if not found.
    """
    n = len(word_tokens)
    for i in range(len(tokens) - n + 1):
        if tokens[i : i + n] != word_tokens:
            continue
        next_pos = i + n
        if next_pos < len(tokens) and tokens[next_pos].startswith("##"):
            continue
        return list(range(i, i + n))
    return []


class SlangClassifier:
    """Classify whether target words are used in their slang sense.

    Builds prototype embeddings for each defined word from example sentences.
    At inference, scores a context by comparing the word's contextual embedding
    to the prototypes.

    Two scoring modes:
      Both senses defined:
        score = cos_sim(context, slang_proto) - cos_sim(context, standard_proto)
        Positive -> slang; negative -> standard.
      Slang examples only:
        score = cos_sim(context, slang_proto)  [0-1 absolute similarity]
    """

    def __init__(self, tokenizer, model, definitions: Dict) -> None:
        self.tokenizer = tokenizer
        self.model = model
        self.prototypes: Dict[str, Tuple[torch.Tensor, Optional[torch.Tensor]]] = {}
        self._build_prototypes(definitions)

    def _embed_word_in_sentence(self, sentence: str, word: str) -> Optional[torch.Tensor]:
        word_tokens = self.tokenizer.tokenize(word)
        if not word_tokens:
            return None
        enc = self.tokenizer(sentence, return_tensors="pt", truncation=True, max_length=512)
        tokens = self.tokenizer.convert_ids_to_tokens(enc["input_ids"][0])
        positions = _find_word_positions(tokens, word_tokens)
        if not positions:
            return None
        with torch.no_grad():
            hidden = self.model(**enc).last_hidden_state[0]  # (L, H)
        return hidden[positions].mean(dim=0)

    def _build_prototypes(self, definitions: Dict) -> None:
        for word, senses in definitions.items():
            word_lc = word.lower()
            slang_embeds, standard_embeds = [], []

            for sentence in senses.get("slang", []):
                emb = self._embed_word_in_sentence(sentence, word_lc)
                if emb is not None:
                    slang_embeds.append(emb)
                else:
                    log.warning("Slang def for '%s': word not found in: %r", word, sentence)

            for sentence in senses.get("standard", []):
                emb = self._embed_word_in_sentence(sentence, word_lc)
                if emb is not None:
                    standard_embeds.append(emb)
                else:
                    log.warning("Standard def for '%s': word not found in: %r", word, sentence)

            if not slang_embeds:
                log.warning("Skipping '%s': no usable slang examples.", word)
                continue

            slang_proto = F.normalize(torch.stack(slang_embeds).mean(0), dim=0)

            if not standard_embeds:
                log.info("  '%s' — %d slang examples, slang-only mode", word_lc, len(slang_embeds))
                self.prototypes[word_lc] = (slang_proto, None)
                continue

            standard_proto = F.normalize(torch.stack(standard_embeds).mean(0), dim=0)
            self.prototypes[word_lc] = (slang_proto, standard_proto)
            log.info("  '%s' — %d slang / %d standard examples",
                     word_lc, len(slang_embeds), len(standard_embeds))

    def score_batch(self, texts: List[str], word: str) -> List[Optional[float]]:
        slang_proto, standard_proto = self.prototypes[word]
        word_tokens = self.tokenizer.tokenize(word)

        enc = self.tokenizer(
            texts, return_tensors="pt", truncation=True, max_length=512, padding=True
        )
        with torch.no_grad():
            hidden = self.model(**enc).last_hidden_state  # (B, L, H)

        results: List[Optional[float]] = []
        for i in range(len(texts)):
            actual_len = int(enc["attention_mask"][i].sum().item())
            tokens = self.tokenizer.convert_ids_to_tokens(enc["input_ids"][i, :actual_len])
            positions = _find_word_positions(tokens, word_tokens)
            if not positions:
                results.append(None)
                continue
            emb = F.normalize(hidden[i, positions].mean(dim=0), dim=0)
            slang_sim = torch.dot(emb, slang_proto).item()
            score = (
                slang_sim - torch.dot(emb, standard_proto).item()
                if standard_proto is not None else slang_sim
            )
            results.append(score)

        return results

    def score_all_rows(self, rows: List[Dict[str, str]], batch_size: int) -> List[Optional[float]]:
        """Score every row. Returns None for rows with no defined slang word present."""
        n = len(rows)
        texts = [r["target_context"] for r in rows]
        scores: List[Optional[float]] = [None] * n

        for word in self.prototypes:
            relevant = [i for i, t in enumerate(texts) if word in t.lower()]
            if not relevant:
                continue
            relevant_texts = [texts[i] for i in relevant]
            batches = list(_batched(relevant_texts, batch_size))
            it = tqdm(batches, desc=f"Slang ({word})", unit="batch", leave=False) if HAS_TQDM else batches
            flat: List[Optional[float]] = []
            for batch in it:
                flat.extend(self.score_batch(batch, word))
            for idx, s in zip(relevant, flat):
                if s is not None and (scores[idx] is None or s > scores[idx]):
                    scores[idx] = s

        return scores

# ---------------------------------------------------------------------------
# Core scoring
# ---------------------------------------------------------------------------

def score_rows(
    rows: List[Dict[str, str]],
    lang_enabled: bool,
    quality_enabled: bool,
    slang_classifier: Optional[SlangClassifier],
    batch_size: int,
    lang_threshold: float,
    quality_threshold: float,
) -> List[Tuple[Dict[str, str], float, float, Optional[float]]]:
    """Run all enabled classifiers. Returns (row, lang, quality, slang) per row."""
    n = len(rows)
    texts = [r["target_context"] for r in rows]
    lang_scores    = [1.0] * n
    quality_scores = [1.0] * n
    slang_scores: List[Optional[float]] = [None] * n

    # ── Language ──────────────────────────────────────────────────────────────
    if lang_enabled:
        if not HAS_LANGDETECT:
            log.warning("langdetect not installed — skipping language filter. pip install langdetect")
        else:
            it = (
                tqdm(enumerate(texts), desc="Language", total=n, unit="row", leave=False)
                if HAS_TQDM else enumerate(texts)
            )
            for i, text in it:
                lang_scores[i] = _english_score(text)

    # ── Quality heuristic (only on language-passing rows) ─────────────────────
    if quality_enabled:
        for i, text in enumerate(texts):
            if lang_scores[i] >= lang_threshold:
                quality_scores[i] = _quality_score(text)

    # ── Slang (only on rows passing both earlier filters) ─────────────────────
    if slang_classifier is not None:
        idx_pass = [
            i for i in range(n)
            if lang_scores[i] >= lang_threshold
            and quality_scores[i] >= quality_threshold
        ]
        pass_scores = slang_classifier.score_all_rows([rows[i] for i in idx_pass], batch_size)
        for i, ss in zip(idx_pass, pass_scores):
            slang_scores[i] = ss

    return list(zip(rows, lang_scores, quality_scores, slang_scores))

# ---------------------------------------------------------------------------
# YAML loader
# ---------------------------------------------------------------------------

def load_slang_definitions(path: Path) -> Dict:
    if not HAS_YAML:
        log.error("--slang-defs requires PyYAML. Install with: pip install pyyaml")
        sys.exit(1)
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        log.error("Slang definitions file must be a YAML mapping of word -> senses.")
        sys.exit(1)
    return data

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Filter word_context.py CSV output using language, quality, and slang filters.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Language + quality only (no torch/transformers needed)
  python bert_filter.py contexts/*.csv -o filtered.csv

  # All three filters
  python bert_filter.py contexts/*.csv -o filtered.csv --slang-defs slang.yaml

  # Score everything for threshold calibration
  python bert_filter.py input.csv -o scored.csv --score-all --keep-scores \\
      --slang-defs slang.yaml
        """,
    )

    parser.add_argument("inputs", nargs="+", metavar="CSV",
                        help="Input CSV file(s) from word_context.py. Glob patterns accepted.")
    parser.add_argument("-o", "--output", required=True, metavar="FILE",
                        help="Output CSV path.")

    # Thresholds
    parser.add_argument("--lang-threshold", type=float, default=0.85, metavar="F",
                        dest="lang_threshold",
                        help="Min English confidence to keep a row (default: 0.85).")
    parser.add_argument("--quality-threshold", type=float, default=0.70, metavar="F",
                        dest="quality_threshold",
                        help="Min heuristic quality score to keep a row (default: 0.70). "
                             "Penalises keyword strings, comma lists, and nav menus.")
    parser.add_argument("--slang-threshold", type=float, default=0.0, metavar="F",
                        dest="slang_threshold",
                        help="Min slang score when a defined slang word is present "
                             "(default: 0.0). For words with both senses: "
                             "slang_sim - standard_sim. For slang-only words: "
                             "absolute cosine similarity (0-1). "
                             "Rows with no defined slang word are unaffected.")

    # Filter toggles
    parser.add_argument("--no-lang-filter", action="store_true", dest="no_lang",
                        help="Skip language detection.")
    parser.add_argument("--no-quality-filter", action="store_true", dest="no_quality",
                        help="Skip writing-quality scoring.")

    # Slang definitions
    parser.add_argument("--slang-defs", default=None, metavar="YAML", dest="slang_defs",
                        help="YAML file of slang word definitions. Slang filter is "
                             "skipped when omitted. Requires torch + transformers.")

    # Output options
    parser.add_argument("--keep-scores", action="store_true", dest="keep_scores",
                        help="Append lang_score, quality_score, slang_score columns.")
    parser.add_argument("--score-all", action="store_true", dest="score_all",
                        help="Write every row without filtering. Implies --keep-scores.")

    # Inference (only relevant when --slang-defs is used)
    parser.add_argument("--batch-size", type=int, default=32, metavar="N", dest="batch_size",
                        help="BERT inference batch size (default: 32).")
    parser.add_argument("--bert-model", default=_BERT_MODEL, metavar="ID", dest="bert_model",
                        help=f"BERT model for slang embeddings (default: {_BERT_MODEL}). "
                             f"Only loaded when --slang-defs is provided.")
    parser.add_argument("--no-quantize", action="store_true", dest="no_quantize",
                        help="Disable int8 dynamic quantization of the BERT model. "
                             "Quantization is on by default and reduces RAM ~4x.")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.score_all:
        args.keep_scores = True

    # Expand glob patterns
    input_paths: List[Path] = []
    for pattern in args.inputs:
        matched = sorted(glob.glob(pattern, recursive=True))
        if matched:
            input_paths.extend(Path(p) for p in matched)
        else:
            input_paths.append(Path(pattern))

    missing = [p for p in input_paths if not p.exists()]
    if missing:
        parser.error(f"File(s) not found: {', '.join(str(p) for p in missing)}")

    # ── Load BERT model (only when --slang-defs is provided) ─────────────────
    slang_classifier: Optional[SlangClassifier] = None
    if args.slang_defs:
        if not HAS_TORCH:
            parser.error(
                "--slang-defs requires torch and transformers.\n"
                "  pip install torch --index-url https://download.pytorch.org/whl/cpu\n"
                "  pip install transformers"
            )
        log.info("Loading BERT model: %s", args.bert_model)
        tokenizer = AutoTokenizer.from_pretrained(args.bert_model)
        model = AutoModel.from_pretrained(args.bert_model).eval()

        if not args.no_quantize:
            log.info("Applying int8 dynamic quantization ...")
            model = torch.quantization.quantize_dynamic(
                model, {torch.nn.Linear}, dtype=torch.qint8
            )

        definitions = load_slang_definitions(Path(args.slang_defs))
        log.info("Building slang prototypes for %d word(s) ...", len(definitions))
        slang_classifier = SlangClassifier(tokenizer, model, definitions)
        log.info("Slang classifier ready (%d word(s) with prototypes).",
                 len(slang_classifier.prototypes))

    if args.no_lang and args.no_quality and slang_classifier is None:
        parser.error("All filters are disabled — nothing to do.")

    # ── Output setup ──────────────────────────────────────────────────────────
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = ["uri", "target_context"]
    if args.keep_scores:
        fieldnames += ["lang_score", "quality_score", "slang_score"]

    grand_in = grand_out = 0

    with output_path.open("w", newline="", encoding="utf-8") as out_fh:
        writer = csv.DictWriter(out_fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()

        for path in input_paths:
            rows = _read_rows(path)
            if not rows:
                log.info("Skipping empty file: %s", path.name)
                continue

            log.info("Processing %s (%d rows) ...", path.name, len(rows))

            scored = score_rows(
                rows=rows,
                lang_enabled=not args.no_lang,
                quality_enabled=not args.no_quality,
                slang_classifier=slang_classifier,
                batch_size=args.batch_size,
                lang_threshold=args.lang_threshold,
                quality_threshold=args.quality_threshold,
            )

            kept = 0
            for row, ls, qs, ss in scored:
                if not args.score_all:
                    if ls < args.lang_threshold:
                        continue
                    if qs < args.quality_threshold:
                        continue
                    if ss is not None and ss < args.slang_threshold:
                        continue

                out_row: Dict = {"uri": row["uri"], "target_context": row["target_context"]}
                if args.keep_scores:
                    out_row["lang_score"]    = f"{ls:.4f}"
                    out_row["quality_score"] = f"{qs:.4f}"
                    out_row["slang_score"]   = f"{ss:.4f}" if ss is not None else ""
                writer.writerow(out_row)
                kept += 1

            grand_in  += len(rows)
            grand_out += kept
            log.info("  %s: %d/%d rows kept (%.1f%%)",
                     path.name, kept, len(rows),
                     100.0 * kept / len(rows) if rows else 0.0)

    log.info("Done. %d/%d rows kept (%.1f%%) -> %s",
             grand_out, grand_in,
             100.0 * grand_out / grand_in if grand_in else 0.0,
             output_path)


if __name__ == "__main__":
    main()
