#!/usr/bin/env python3
"""
bert_filter.py — Filter word_context.py CSV output using BERT-based classifiers.

Three classifiers run on each target_context chunk:

  1. Language — langdetect (lightweight rule-based library, no neural model)
     Drops rows where English-language probability < --lang-threshold (default 0.85).

  2. Writing quality — textattack/bert-base-uncased-CoLA (classification head)
     BERT base fine-tuned on the Corpus of Linguistic Acceptability.
     Drops rows where "acceptable" confidence < --quality-threshold (default 0.70).
     Keyword strings, SEO spam, and nav menus score poorly here.

  3. Slang sense disambiguation — shares the same BERT backbone as quality
     Extracts the word's contextual embedding from the last hidden layer and
     compares it to prototype embeddings built from user-supplied examples.
     Words with both senses: score = cos_sim(context, slang_proto) - cos_sim(context, standard_proto).
     Words with slang examples only: score = cos_sim(context, slang_proto) (0-1 absolute).
     Drops rows where a defined slang word appears but scores below
     --slang-threshold (default 0.0).
     Rows containing no defined slang word are not affected by this filter.

All three filters can be disabled independently. Use --score-all to write every
row with scores attached (useful for calibrating thresholds).

"Embeddings" for slang classification are generated using samples in slang.yaml.
The yaml content was generated by Claude Sonnet 4.6 and manually edited.

Usage:
    python bert_filter.py contexts/*.csv -o filtered.csv --slang-defs slang.yaml
    python bert_filter.py input.csv -o scored.csv --score-all --keep-scores
    python bert_filter.py input.csv -o out.csv --no-lang-filter
    python bert_filter.py input.csv -o out.csv --slang-defs slang.yaml --slang-threshold 0.05
"""

from __future__ import annotations

import argparse
import csv
import glob
import logging
import os
import sys
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Tuple

os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

try:
    import torch
    import torch.nn.functional as F
    from transformers import (  # type: ignore
        AutoModelForSequenceClassification,
        AutoTokenizer,
    )
except ImportError:
    print(
        "ERROR: transformers and torch are required.\n"
        "  pip install transformers torch",
        file=sys.stderr,
    )
    sys.exit(1)

try:
    from langdetect import DetectorFactory, LangDetectException, detect_langs  # type: ignore
    DetectorFactory.seed = 0  # reproducible results
    HAS_LANGDETECT = True
except ImportError:
    HAS_LANGDETECT = False

try:
    import yaml  # type: ignore
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

try:
    from tqdm import tqdm  # type: ignore
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(line_buffering=True)  # type: ignore[attr-defined]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stderr)],
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Default model — shared for quality scoring and slang embeddings
# ---------------------------------------------------------------------------

_BERT_MODEL = "textattack/bert-base-uncased-CoLA"

# ---------------------------------------------------------------------------
# Language detection (langdetect, no neural model)
# ---------------------------------------------------------------------------

def _english_score(text: str) -> float:
    """Return estimated probability that text is English via langdetect."""
    try:
        for lang in detect_langs(text):
            if lang.lang == "en":
                return float(lang.prob)
        return 0.0
    except LangDetectException:
        return 0.0

# ---------------------------------------------------------------------------
# CSV helpers
# ---------------------------------------------------------------------------

def _read_rows(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _batched(items: list, size: int) -> Iterator[list]:
    for i in range(0, len(items), size):
        yield items[i : i + size]

# ---------------------------------------------------------------------------
# Quality scoring (CoLA classification head on shared BERT)
# ---------------------------------------------------------------------------

def _quality_scores(
    texts: List[str],
    tokenizer,
    model,
    batch_size: int,
) -> List[float]:
    """Return CoLA acceptability confidence (LABEL_1) for each text."""
    scores: List[float] = []
    batches = list(_batched(texts, batch_size))
    it = tqdm(batches, desc="Quality", unit="batch", leave=False) if HAS_TQDM else batches
    for batch in it:
        enc = tokenizer(
            batch, return_tensors="pt", truncation=True, max_length=512, padding=True
        )
        with torch.no_grad():
            logits = model(**enc).logits  # (B, num_labels)
        probs = torch.softmax(logits, dim=-1)
        scores.extend(probs[:, 1].tolist())  # index 1 = LABEL_1 = acceptable
    return scores

# ---------------------------------------------------------------------------
# Slang sense classifier (hidden states from shared BERT)
# ---------------------------------------------------------------------------

def _find_word_positions(tokens: List[str], word_tokens: List[str]) -> List[int]:
    """Return token positions of the first full-word occurrence of word_tokens.

    A full-word match requires that the token immediately after the match is
    not a WordPiece continuation (## prefix), preventing e.g. 'fire' from
    matching inside 'fired' when BERT splits it as ['fire', '##d'].
    Returns [] if not found.
    """
    n = len(word_tokens)
    for i in range(len(tokens) - n + 1):
        if tokens[i : i + n] != word_tokens:
            continue
        next_pos = i + n
        if next_pos < len(tokens) and tokens[next_pos].startswith("##"):
            continue
        return list(range(i, i + n))
    return []


def _last_hidden(model, enc: Dict) -> torch.Tensor:
    """Return the last encoder layer's hidden states from a ForSequenceClassification model."""
    return model(**enc, output_hidden_states=True).hidden_states[-1]


class SlangClassifier:
    """Classify whether target words are used in their slang sense.

    At construction, builds prototype embeddings for each defined word by
    encoding example sentences with BERT and averaging the contextual
    embeddings of the target word across all examples per sense.

    Two scoring modes depending on which senses are defined:

      Both slang + standard examples present (normal mode):
        score = cos_sim(context_emb, slang_proto) - cos_sim(context_emb, standard_proto)
        Positive -> slang sense; negative -> standard sense.

      Slang examples only (no standard sense defined):
        score = cos_sim(context_emb, slang_proto)
        Ranges 0-1; higher -> embedding is closer to the slang prototype.
        Use --slang-threshold to set a minimum absolute similarity.
    """

    def __init__(self, tokenizer, model, definitions: Dict) -> None:
        self.tokenizer = tokenizer
        self.model = model
        self.prototypes: Dict[str, Tuple[torch.Tensor, Optional[torch.Tensor]]] = {}
        self._build_prototypes(definitions)

    # ── Prototype construction ────────────────────────────────────────────────

    def _embed_word_in_sentence(
        self, sentence: str, word: str
    ) -> Optional[torch.Tensor]:
        """Return the mean last-layer hidden state for word's tokens in sentence."""
        word_tokens = self.tokenizer.tokenize(word)
        if not word_tokens:
            return None

        enc = self.tokenizer(
            sentence, return_tensors="pt", truncation=True, max_length=512
        )
        tokens = self.tokenizer.convert_ids_to_tokens(enc["input_ids"][0])

        positions = _find_word_positions(tokens, word_tokens)
        if not positions:
            return None

        hidden = _last_hidden(self.model, enc)[0]  # (L, H)
        return hidden[positions].mean(dim=0)

    def _build_prototypes(self, definitions: Dict) -> None:
        for word, senses in definitions.items():
            word_lc = word.lower()
            slang_embeds, standard_embeds = [], []

            for sentence in senses.get("slang", []):
                emb = self._embed_word_in_sentence(sentence, word_lc)
                if emb is not None:
                    slang_embeds.append(emb)
                else:
                    log.warning(
                        "Slang definition for '%s': word not found in example: %r",
                        word, sentence,
                    )

            for sentence in senses.get("standard", []):
                emb = self._embed_word_in_sentence(sentence, word_lc)
                if emb is not None:
                    standard_embeds.append(emb)
                else:
                    log.warning(
                        "Standard definition for '%s': word not found in example: %r",
                        word, sentence,
                    )

            if not slang_embeds:
                log.warning(
                    "Skipping '%s': need at least one usable slang example.", word
                )
                continue

            slang_proto = F.normalize(torch.stack(slang_embeds).mean(0), dim=0)

            if not standard_embeds:
                log.info(
                    "  '%s' — %d slang examples, no standard sense (slang-only mode)",
                    word_lc, len(slang_embeds),
                )
                self.prototypes[word_lc] = (slang_proto, None)
                continue

            standard_proto = F.normalize(torch.stack(standard_embeds).mean(0), dim=0)
            self.prototypes[word_lc] = (slang_proto, standard_proto)
            log.info(
                "  '%s' — %d slang / %d standard examples",
                word_lc, len(slang_embeds), len(standard_embeds),
            )

    # ── Batch inference ───────────────────────────────────────────────────────

    def score_batch(
        self, texts: List[str], word: str
    ) -> List[Optional[float]]:
        """Score a list of texts for slang usage of word.

        Returns a list of floats or None where the word's tokens could not be
        located in the context. Score meaning depends on prototype mode:
          - Both senses: slang_sim - standard_sim (positive = slang)
          - Slang only:  cos_sim(emb, slang_proto) (0-1 absolute similarity)
        """
        slang_proto, standard_proto = self.prototypes[word]
        word_tokens = self.tokenizer.tokenize(word)

        enc = self.tokenizer(
            texts,
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True,
        )
        hidden = _last_hidden(self.model, enc)  # (B, L, H)

        results: List[Optional[float]] = []
        for i in range(len(texts)):
            actual_len = int(enc["attention_mask"][i].sum().item())
            tokens = self.tokenizer.convert_ids_to_tokens(
                enc["input_ids"][i, :actual_len]
            )
            positions = _find_word_positions(tokens, word_tokens)
            if not positions:
                results.append(None)
                continue

            emb = F.normalize(hidden[i, positions].mean(dim=0), dim=0)
            slang_sim = torch.dot(emb, slang_proto).item()
            score = (
                slang_sim - torch.dot(emb, standard_proto).item()
                if standard_proto is not None
                else slang_sim
            )
            results.append(score)

        return results

    def score_all_rows(
        self,
        rows: List[Dict[str, str]],
        batch_size: int,
    ) -> List[Optional[float]]:
        """Return a slang score for each row.

        For each defined word, runs batched inference over the rows that
        contain that word. If multiple defined words appear in one row, the
        highest score is kept (most slang-like interpretation wins).
        Returns None for rows containing no defined slang word.
        """
        n = len(rows)
        texts = [r["target_context"] for r in rows]
        scores: List[Optional[float]] = [None] * n

        for word in self.prototypes:
            relevant = [i for i, t in enumerate(texts) if word in t.lower()]
            if not relevant:
                continue

            relevant_texts = [texts[i] for i in relevant]
            batches = list(_batched(relevant_texts, batch_size))
            desc = f"Slang ({word})"
            it = tqdm(batches, desc=desc, unit="batch", leave=False) if HAS_TQDM else batches

            flat: List[Optional[float]] = []
            for batch in it:
                flat.extend(self.score_batch(batch, word))

            for idx, s in zip(relevant, flat):
                if s is not None and (scores[idx] is None or s > scores[idx]):
                    scores[idx] = s

        return scores

# ---------------------------------------------------------------------------
# Core filtering
# ---------------------------------------------------------------------------

def score_rows(
    rows: List[Dict[str, str]],
    lang_enabled: bool,
    quality_enabled: bool,
    bert_tokenizer,
    bert_model,
    slang_classifier: Optional[SlangClassifier],
    batch_size: int,
    lang_threshold: float,
    quality_threshold: float,
) -> List[Tuple[Dict[str, str], float, float, Optional[float]]]:
    """Run all enabled classifiers. Returns (row, lang, quality, slang) per row.

    Slang is None for rows where no defined slang word appears in the context.
    Each later pass skips rows that already failed an earlier threshold.
    """
    n = len(rows)
    texts = [r["target_context"] for r in rows]
    lang_scores    = [1.0] * n
    quality_scores = [1.0] * n
    slang_scores: List[Optional[float]] = [None] * n

    # ── Language ──────────────────────────────────────────────────────────────
    if lang_enabled:
        if not HAS_LANGDETECT:
            log.warning(
                "langdetect not installed — language filter disabled. "
                "Install with: pip install langdetect"
            )
        else:
            it = (
                tqdm(enumerate(texts), desc="Language", total=n, unit="row", leave=False)
                if HAS_TQDM else enumerate(texts)
            )
            for i, text in it:
                lang_scores[i] = _english_score(text)

    # ── Quality (only on language-passing rows) ───────────────────────────────
    if quality_enabled and bert_model is not None:
        idx_pass = [i for i, ls in enumerate(lang_scores) if ls >= lang_threshold]
        q_flat = _quality_scores(
            [texts[i] for i in idx_pass], bert_tokenizer, bert_model, batch_size
        )
        for i, qs in zip(idx_pass, q_flat):
            quality_scores[i] = qs

    # ── Slang (only on rows passing both earlier filters) ─────────────────────
    if slang_classifier is not None:
        idx_pass = [
            i for i in range(n)
            if lang_scores[i] >= lang_threshold
            and quality_scores[i] >= quality_threshold
        ]
        pass_scores = slang_classifier.score_all_rows(
            [rows[i] for i in idx_pass], batch_size
        )
        for i, ss in zip(idx_pass, pass_scores):
            slang_scores[i] = ss

    return list(zip(rows, lang_scores, quality_scores, slang_scores))

# ---------------------------------------------------------------------------
# YAML loader
# ---------------------------------------------------------------------------

def load_slang_definitions(path: Path) -> Dict:
    if not HAS_YAML:
        log.error(
            "--slang-defs requires PyYAML. Install with: pip install pyyaml"
        )
        sys.exit(1)
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        log.error("Slang definitions file must be a YAML mapping of word -> senses.")
        sys.exit(1)
    return data

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Filter word_context.py CSV output using BERT-based classifiers.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # All three filters
  python bert_filter.py contexts/*.csv -o filtered.csv --slang-defs slang.yaml

  # Calibrate thresholds: write every row with all scores
  python bert_filter.py input.csv -o scored.csv --score-all --keep-scores \\
      --slang-defs slang.yaml

  # Language + quality only (no slang definitions available yet)
  python bert_filter.py contexts/*.csv -o filtered.csv

  # Stricter slang gate
  python bert_filter.py input.csv -o out.csv --slang-defs slang.yaml \\
      --slang-threshold 0.05
        """,
    )

    parser.add_argument("inputs", nargs="+", metavar="CSV",
                        help="Input CSV file(s) from word_context.py. Glob patterns accepted.")
    parser.add_argument("-o", "--output", required=True, metavar="FILE",
                        help="Output CSV path.")

    # Thresholds
    parser.add_argument("--lang-threshold", type=float, default=0.85, metavar="F",
                        dest="lang_threshold",
                        help="Min English confidence to keep a row (default: 0.85).")
    parser.add_argument("--quality-threshold", type=float, default=0.70, metavar="F",
                        dest="quality_threshold",
                        help="Min linguistic-acceptability confidence to keep (default: 0.70).")
    parser.add_argument("--slang-threshold", type=float, default=0.0, metavar="F",
                        dest="slang_threshold",
                        help="Min slang score to keep a row when a defined slang word is "
                             "present (default: 0.0). For words with both slang and standard "
                             "examples the score is slang_sim - standard_sim (positive = slang). "
                             "For slang-only words (no standard examples) it is an absolute "
                             "cosine similarity (0-1); consider raising the threshold to ~0.5 "
                             "for those. Rows with no defined slang word are unaffected.")

    # Filter toggles
    parser.add_argument("--no-lang-filter", action="store_true", dest="no_lang",
                        help="Skip language detection.")
    parser.add_argument("--no-quality-filter", action="store_true", dest="no_quality",
                        help="Skip writing-quality classification.")

    # Slang definitions
    parser.add_argument("--slang-defs", default=None, metavar="YAML", dest="slang_defs",
                        help="YAML file of slang word definitions (see script docstring). "
                             "Slang filter is skipped when omitted.")

    # Output options
    parser.add_argument("--keep-scores", action="store_true", dest="keep_scores",
                        help="Append lang_score, quality_score, slang_score columns.")
    parser.add_argument("--score-all", action="store_true", dest="score_all",
                        help="Write every row without filtering. Implies --keep-scores. "
                             "Useful for calibrating thresholds.")

    # Inference
    parser.add_argument("--batch-size", type=int, default=32, metavar="N", dest="batch_size",
                        help="Inference batch size (default: 32).")

    # Model override
    parser.add_argument("--bert-model", default=_BERT_MODEL, metavar="ID", dest="bert_model",
                        help=f"BERT checkpoint used for quality scoring and slang embeddings "
                             f"(default: {_BERT_MODEL}).")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.score_all:
        args.keep_scores = True

    # Expand glob patterns
    input_paths: List[Path] = []
    for pattern in args.inputs:
        matched = sorted(glob.glob(pattern, recursive=True))
        if matched:
            input_paths.extend(Path(p) for p in matched)
        else:
            input_paths.append(Path(pattern))

    missing = [p for p in input_paths if not p.exists()]
    if missing:
        parser.error(f"File(s) not found: {', '.join(str(p) for p in missing)}")

    # ── Load shared BERT model (quality + slang) ──────────────────────────────
    bert_tokenizer = bert_model = None
    need_bert = (not args.no_quality) or bool(args.slang_defs)
    if need_bert:
        log.info("Loading BERT model: %s", args.bert_model)
        bert_tokenizer = AutoTokenizer.from_pretrained(args.bert_model)
        bert_model = (
            AutoModelForSequenceClassification
            .from_pretrained(args.bert_model)
            .eval()
        )
        log.info("BERT model loaded.")

    # ── Load slang classifier ─────────────────────────────────────────────────
    slang_classifier: Optional[SlangClassifier] = None
    if args.slang_defs:
        definitions = load_slang_definitions(Path(args.slang_defs))
        log.info("Building slang prototypes for %d word(s) ...", len(definitions))
        slang_classifier = SlangClassifier(bert_tokenizer, bert_model, definitions)
        log.info(
            "Slang classifier ready (%d word(s) with prototypes).",
            len(slang_classifier.prototypes),
        )

    if args.no_lang and args.no_quality and slang_classifier is None:
        parser.error("All filters are disabled — nothing to do.")

    # ── Output setup ──────────────────────────────────────────────────────────
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = ["uri", "target_context"]
    if args.keep_scores:
        fieldnames += ["lang_score", "quality_score", "slang_score"]

    grand_in = grand_out = 0

    with output_path.open("w", newline="", encoding="utf-8") as out_fh:
        writer = csv.DictWriter(out_fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()

        for path in input_paths:
            rows = _read_rows(path)
            if not rows:
                log.info("Skipping empty file: %s", path.name)
                continue

            log.info("Processing %s (%d rows) ...", path.name, len(rows))

            scored = score_rows(
                rows=rows,
                lang_enabled=not args.no_lang,
                quality_enabled=not args.no_quality,
                bert_tokenizer=bert_tokenizer,
                bert_model=bert_model,
                slang_classifier=slang_classifier,
                batch_size=args.batch_size,
                lang_threshold=args.lang_threshold,
                quality_threshold=args.quality_threshold,
            )

            kept = 0
            for row, ls, qs, ss in scored:
                if not args.score_all:
                    if ls < args.lang_threshold:
                        continue
                    if qs < args.quality_threshold:
                        continue
                    if ss is not None and ss < args.slang_threshold:
                        continue

                out_row: Dict = {
                    "uri": row["uri"],
                    "target_context": row["target_context"],
                }
                if args.keep_scores:
                    out_row["lang_score"]    = f"{ls:.4f}"
                    out_row["quality_score"] = f"{qs:.4f}"
                    out_row["slang_score"]   = f"{ss:.4f}" if ss is not None else ""
                writer.writerow(out_row)
                kept += 1

            grand_in  += len(rows)
            grand_out += kept
            log.info(
                "  %s: %d/%d rows kept (%.1f%%)",
                path.name, kept, len(rows),
                100.0 * kept / len(rows) if rows else 0.0,
            )

    log.info(
        "Done. %d/%d rows kept (%.1f%%) -> %s",
        grand_out, grand_in,
        100.0 * grand_out / grand_in if grand_in else 0.0,
        output_path,
    )


if __name__ == "__main__":
    main()
